### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by ButylLee** [lynnboy/CppCoreGuidelines-zh-CN#11]
[这里](https://github.com/lynnboy/CppCoreGuidelines-zh-CN/blob/master/CppCoreGuidelines-zh-CN.md#faq2-%E8%BF%99%E9%A1%B9%E5%B7%A5%E4%BD%9C%E5%AE%A4%E4%BD%95%E6%97%B6%E4%BD%95%E5%9C%B0%E9%A6%96%E6%AC%A1%E5%85%AC%E5%BC%80%E7%9A%84)
室->是

**Comment by ButylLee** [comment]
又发现一个：

https://github.com/lynnboy/CppCoreGuidelines-zh-CN/blob/master/CppCoreGuidelines-zh-CN.md#%E6%B3%A8%E8%A7%A3-101

编译期->编译器

**Comment by ButylLee** [comment]
https://github.com/lynnboy/CppCoreGuidelines-zh-CN/blob/master/CppCoreGuidelines-zh-CN.md#%E6%B3%A8%E8%A7%A3-101

默认操作是一个概念上向配合的集合

向配合->相配合

**Comment by ButylLee** [comment]
[示例](https://github.com/lynnboy/CppCoreGuidelines-zh-CN/blob/master/CppCoreGuidelines-zh-CN.md#%E7%A4%BA%E4%BE%8B-84)

中最后一行，“折导致”->"这导致"

**Comment by ButylLee** [comment]
[这里](https://github.com/lynnboy/CppCoreGuidelines-zh-CN/blob/master/CppCoreGuidelines-zh-CN.md#%E6%B3%A8%E8%A7%A3-394) 的第二段第三行，"层导致"->“曾导致”，"这中做法"->"这种做法"

**Comment by ButylLee** [comment]
[这里](https://github.com/lynnboy/CppCoreGuidelines-zh-CN/blob/master/CppCoreGuidelines-zh-CN.md#%E4%BE%8B%E5%A4%96-55) 第一行末尾，"并在适当是"->"并在适当时"

**Comment by ButylLee** [comment]
[这里](https://github.com/lynnboy/CppCoreGuidelines-zh-CN/blob/master/CppCoreGuidelines-zh-CN.md#c17-%E5%92%8C-c30-%E7%A4%BA%E4%BE%8B) 的标题中，"C++30"->"C++20"

**Comment by ButylLee** [comment]
[这一节](https://github.com/lynnboy/CppCoreGuidelines-zh-CN/blob/master/CppCoreGuidelines-zh-CN.md#%E7%A4%BA%E4%BE%8B%E4%B8%8D%E5%A5%BD-128) 最后面的链接括号括多了，链接应为"xxx.pdf"而不是"xxx.pdf)。"

**Comment by lynnboy** [comment]
多谢
