### ISSUE TITLE
词汇翻译建议

### ISSUE THREAD

**Issue by ButylLee** [lynnboy/CppCoreGuidelines-zh-CN#12]
[此处](https://github.com/lynnboy/CppCoreGuidelines-zh-CN/blob/master/CppCoreGuidelines-zh-CN.md#%E6%B3%A8%E8%A7%A3-395)

“栈展开”建议翻译为“栈回溯”

见：[throw页面的栈回溯节](https://zh.cppreference.com/w/cpp/language/throw)

**Comment by lynnboy** [comment]
多谢
