### ISSUE TITLE
github page deployment error

### ISSUE THREAD

**Issue by benfre** [lynnboy/CppCoreGuidelines-zh-CN#21]
The build step of the GitHub Page deployment has error, pages cannot visit.

The original English version also use GitHub pages. There is a [instruction file](https://github.com/isocpp/CppCoreGuidelines/blob/gh-pages/INSTRUCTIONS.txt) on the gh-pages branch. The fifth step is `5. Replace all instances of {{ with {{ "{{" }}`

I tried enclosure the code block with` {% raw %} {% endraw %}`. It also works.

By the way, can we copy the template and js script from that branch, and have the option to hide all code blocks?

**Comment by lynnboy** [comment]
You are welcome!
Feel free to fork and send PR 😄

**Comment by benfre** [comment]
Errors have been fixed.
