### ISSUE TITLE
I.2: 避免非 `const` 全局变量描述感觉有点抽象

### ISSUE THREAD

**Issue by Mq-b** [lynnboy/CppCoreGuidelines-zh-CN#25]
你们描述的是：
> 非 `const` 全局变量能够隐藏依赖关系，并使这些依赖项可能出现无法预测的变动。

感觉说的太抽象了，我能懂只是因为我懂全局变量的问题，而不是我看它看懂的。

`《C++ Guidelines 解析》` 里面的描述是这样的：
> 全局变量会在函数中注入隐藏的依赖，而该依赖并不是接口的一部分。

虽然也有点抽象，但是我觉得这个描述要更好的多，因为我认为它后半句 **该依赖并不是接口的一部分** 描述的比较形象一些，虽然也就那样吧🤣🤣。

**Comment by kouzhudong** [comment]
不是const的全局变量
